### ISSUE TITLE
Seemingly wrong synchronize scaling handling

### ISSUE THREAD

**Issue by function2-llx** [MIC-DKFZ/batchgeneratorsv2#5]
In the following code, it seems that when `np.random.uniform() < self.p_synchronize_scaling_across_axes`, the scaling should be synchronized across axes.

https://github.com/MIC-DKFZ/batchgeneratorsv2/blob/c4f7b8d43bef7e70f30ad7a3de39f2b46c795e56/batchgeneratorsv2/transforms/spatial/spatial.py#L59-L61

**Comment by mibaumgartner** [comment]
Dear @function2-llx ,

good catch! Thank you for the bug report, we have created a Pull Request to fix it :)

Best,
Michael
